import type { Roadmap, Task } from "./roadmap";
const task = (id: string, title: string, owner: string, dependsOn: string[], description: string, criteria: string[], parentId: string | null = null, status: Task["status"] = "todo"): Task => ({ id, title, owner, dependsOn, description, criteria, parentId, status });
export const sampleRoadmap: Roadmap = {
  version: 1, title: "Container registry onboarding", application: "Payments API · example",
  tasks: [
    task("intake", "Confirm application requirements", "Application team", [], "Agree on the application owner, image naming convention, target environments, and registry requirements before starting the parallel workstreams.", ["Application owner is recorded", "Target environments and image naming are agreed"], null, "done"),
    task("registry", "Registry setup", "Platform team", ["intake"], "Prepare a dedicated image repository and the access needed by the build pipeline. Retention can be configured independently of service-account work.", ["Repository and access are ready", "Retention policy is configured"]),
    task("repository", "Create image repository", "Platform team", [], "Create the application repository in the registry using the agreed naming convention.", ["Repository exists with the agreed name", "Repository URL is recorded"], "registry", "done"),
    task("identity", "Create CI service account", "Platform team", ["repository"], "Create a dedicated identity for the pipeline. Keep credentials in your approved secrets manager.", ["CI identity is created", "Credential reference is recorded in the approved secrets manager"], "registry", "in-progress"),
    task("permissions", "Verify push permissions", "Platform team", ["identity"], "Grant the CI identity the required repository access and verify it can authenticate and push a test image.", ["Access is scoped to the required repository", "Authentication and a test push succeed"], "registry"),
    task("retention", "Set retention policy", "Platform team", ["repository"], "Configure how image versions are retained. Coordinate the policy with release rollback needs.", ["Retention rules are configured", "Required rollback images are protected"], "registry"),
    task("container", "Container preparation", "Application team", ["intake"], "Prepare and test a reproducible container image for the application.", ["The image builds and passes the agreed checks"]),
    task("dockerfile", "Prepare Dockerfile", "Application team", [], "Choose an approved base image and define the build and runtime stages for the application.", ["Base image is approved", "Dockerfile and build context are committed"], "container", "done"),
    task("build", "Build and test image", "Application team", ["dockerfile"], "Build the image and run the application checks against the resulting container.", ["Image builds reproducibly", "Application checks pass inside the container"], "container"),
    task("network", "Network access", "Network team", ["intake"], "Establish access from build runners and the environment that will pull the image.", ["Required registry connections are verified"]),
    task("runner-access", "Verify build-runner access", "Network team", [], "Verify DNS resolution and HTTPS connectivity from the build runner to the registry.", ["Registry hostname resolves", "Runner connects over the required HTTPS endpoint"], "network"),
    task("runtime-access", "Verify target-environment access", "Network team", [], "Verify the target environment can reach the registry before the final image-pull check.", ["Registry hostname resolves in the target environment", "Required network access is available"], "network"),
    task("validation", "Publish & verify", "Application team", [], "Bring the parallel workstreams together, publish the image, verify it, and complete the handover.", ["Image is published and verified", "All required work is complete"]),
    task("pipeline", "Publish image from CI", "Application team", ["permissions", "build", "runner-access"], "Connect the pipeline to the registry, build the application, and publish an immutable image version. This can start after push access, image tests, and runner connectivity are ready; it does not wait for retention configuration.", ["Pipeline publishes the image successfully", "Image digest and version are recorded"], "validation"),
    task("scan", "Pass required image checks", "Security team", ["pipeline"], "Run the image through your organization's required security and policy checks.", ["Required image checks pass", "Any exceptions are reviewed through the agreed process"], "validation"),
    task("pull", "Verify image pull", "Platform team", ["scan", "runtime-access"], "Pull the published image from the target environment using its intended identity.", ["Target environment authenticates successfully", "The exact published image digest can be pulled"], "validation"),
    task("complete", "Onboarding complete", "Application team", ["pull", "registry", "container", "network"], "Confirm the application is ready to use the registry and hand over the operational information to its owners.", ["All required onboarding work is complete", "Application owner has the repository, pipeline, and support links"], "validation"),
  ],
};
